### ISSUE TITLE
Does developer need to run `dfx start` at current terminal when exec `upgrade-canister.sh` script?

### ISSUE THREAD

**Issue by q2333gh** [open-chat-labs/open-chat#5400]
https://github.com/open-chat-labs/open-chat/blob/d8d2ef4cdf64ffabe91cf2847a5cb5a803ed73ec/scripts/upgrade-canister.sh#L4

**Comment by hpeebles** [comment]
If you are upgrading a local canister then you'll need to have DFX running locally and then you can run `./scripts/upgrade-canister-local.sh`

**Comment by q2333gh** [comment]
Thank you ! It really helps and worked~
