### ISSUE TITLE
Readme.md is insufficient to have a working local deployment of Openchat

### ISSUE THREAD

**Issue by let4be** [open-chat-labs/open-chat#5481]
Trying to deploy locally and followed readme(installed dfx, npm, cc, cmake, rust)
Tip of the master branch at: https://github.com/open-chat-labs/open-chat/tree/9b9f85b16d70e8c6a56ad3bf2150821d8cebb763

I had to additionally install `build-esstential` and `cmake` on my Ubuntu(not mentioned in readme)
After loading a local front-end on http://127.0.0.1:5001/
I see the following in browser dev console:
```
Error: Canister ID is required, but received undefined instead. If you are using automatically generated declarations, this may be because your application is not setting the canister ID in process.env correctly.
```
however `readme.md` doesn't mention setting this anywhere

Any advice?

**Comment by let4be** [comment]
Anyone? 

I would really like to poke with openchat locally but this is blocking for me :(

**Comment by let4be** [comment]
after another try with a clean install it launched! buuuut Im getting "IC0301: Canister qhbym-qaaaa-aaaaa-aaafq-cai not found"
Looks like it's an icrc token index canister, will try to figure it out today
probably need local copy deployed with dfx

**Comment by let4be** [comment]
ugh... it finally started, looks like there were some remnants/corrupted state in ~/.config/dfx
(from my previous deployment attempts)

should start with a clean ~/.config/dfx

**Comment by hpeebles** [comment]
Hey!

I'm glad you got it working in the end.

Feel free to message me on OpenChat is you run into any more issues, my username is simply 'Hamish'.
