### ISSUE TITLE
Where do you impl  `attachFile`  funtion in canister? 

### ISSUE THREAD

**Issue by q2333gh** [open-chat-labs/open-chat#5570]
I searched for source code but not found out. 
Its a very useful function in canister !
![image](https://github.com/open-chat-labs/open-chat/assets/32679742/fe7a6057-b280-4eb2-8505-2514b4b95840)

**Comment by hpeebles** [comment]
When a user sends a message with an attachment we first upload the attachment, then we send the message with a reference to the attachment.

See `uploadFile` here - https://github.com/open-chat-labs/open-chat/blob/master/frontend/openchat-agent/src/services/data/data.client.ts#L55

**Comment by q2333gh** [comment]
Very helpful! Thanks alot ! Happy~

**Comment by q2333gh** [comment]
Got rust impl at here ! 
`backend/canisters/storage_bucket/impl/src/updates/upload_chunk.rs` line 18 function  upload_chunk_impl()
