### ISSUE TITLE
FAILED VERIFICATION

### ISSUE THREAD

**Issue by AdorableAnn** [open-chat-labs/open-chat#6544]
Internet Computer Id verification failed.
How can this be solved?

**Comment by AdorableAnn** [comment]
![Uploading Screenshot_20241010-073407.png…]()

**Comment by julianjelfs** [comment]
As I mentioned in the other issue you raised, this should be taken up with DecideAI [here](https://oc.app/community/zmr66-uyaaa-aaaar-askta-cai/channel/147659463637015253859440282407289390537)
