### ISSUE TITLE
DECIDE ID PROFILE

### ISSUE THREAD

**Issue by AdorableAnn** [open-chat-labs/open-chat#6545]
Internet Computer Id verification failed.
How can this be solved?
![Screenshot_20241010-073407](https://github.com/user-attachments/assets/c3ab8875-7f5b-4fd8-af5e-61cdb7575197)

**Comment by julianjelfs** [comment]
I'm afraid that this is something that will need to be addressed by talking to DecideAI. It's beyond the control of the OpenChat team. I would suggest that you contact them [here](https://oc.app/community/zmr66-uyaaa-aaaar-askta-cai/channel/147659463637015253859440282407289390537)
